#!/usr/bin/python
# check_nginx is a nagios_script to monitor nginx status
# Original by: yangzi2008@126.com , http://www.nginxs.com
# Fixed by Alexey Malov <scukonick@gmail.com>
# TODO: rewrite for python3

import string
try:
    import urllib.request as urllib2
except:
    import urllib2
import sys
import logging
import argparse
logging.basicConfig(format='%(asctime)s %(message)s', filename='/tmp/nginx_check.log', level=logging.DEBUG)


parser = argparse.ArgumentParser()
parser.add_argument('url', metavar='URL')
parser.add_argument('metric', metavar='METRIC')
args = parser.parse_args()

result = {
    'accepted': 0,
    'handled': 0,
    'requests': 0,
    'reading': 0,
    'writing': 0,
    'waiting': 0,
}

response = urllib2.urlopen(args.url)
the_page = response.readline()
conn = the_page.split()
ActiveConn = int(conn[2].decode("utf-8"))
the_page1 = response.readline()
the_page2 = response.readline()
a = the_page2.split()
result['accepted'] = int(a[0].decode("utf-8"))
result['handled'] = int(a[1].decode("utf-8"))
result['requests'] = int(a[2].decode("utf-8"))

the_page3 = response.readline()
response.close()
b = the_page3.split()
result['reading'] = int(b[1].decode("utf-8"))
result['writing'] = int(b[3].decode("utf-8"))
result['waiting'] = int(b[5].decode("utf-8"))
print(result[args.metric])




